packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  electron: true
  esbuild: true
  electron-winstaller: false
  '@parcel/watcher': false
  node-pty: true
minimumReleaseAgeExclude:
  - eslint@10.6.0
  - prettier@3.9.0
