// Public barrel for the transport layer.
export { bridgeClient } from './client';
export type { BridgeClient } from './client';
export type {
  Repository,
  Project,
  InstallManifest,
  AgentKind,
  LoadConfigResult,
  SectionValidity,
  SkillKeeperConfig,
  GeneralConfig,
  UpdatesConfig,
  AgentsConfig,
  NotificationsConfig,
  RepositoriesConfig,
  ProjectsConfig,
  OnboardingState,
  Lang,
  EditorOption,
  OpenResult,
  RepoResult,
  RemoveResult,
  RepoInfo,
  AvailableSkill,
  ProjectResult,
  ProjectInfo,
  SkillRef,
  ApplyArgs,
  ApplyProgress,
  ApplyResult,
  AvailableMcp,
  McpInstallReq,
  McpBatch,
  ApplyMcpArgs,
  ApplyMcpResult,
  McpInstall,
  McpUpdateReq,
  UpdateMcpArgs,
  UpdateMcpResult,
  McpUpdatePreflightArgs,
  McpUpdatePreflightResult,
  McpServerDef,
  McpTransport,
  McpIdentity,
  McpPresetOrigin,
} from './types';
